create sequence app_user_id_seq
    maxvalue 99999999;

alter sequence app_user_id_seq owner to user_management_user;

create sequence otp_id_seq
    maxvalue 999999999;

alter sequence otp_id_seq owner to user_management_user;

create table app_user
(
    id                     bigint generated by default as identity (maxvalue 99999999)
        constraint app_user_pk
            primary key,
    name                   varchar,
    email                  varchar,
    creation_date          timestamp,
    last_modification_date timestamp,
    mobile_number          varchar
);

alter table app_user
    owner to user_management_user;

alter sequence app_user_id_seq owned by app_user.id;

create table otp
(
    id                     bigint generated by default as identity (maxvalue 999999999)
        constraint otp_pk
            primary key,
    user_id                integer
        constraint otp_app_user_id_fk
            references app_user,
    otp_number             varchar,
    creation_date          timestamp,
    last_modification_date timestamp,
    email                  varchar
);

alter table otp
    owner to user_management_user;

alter sequence otp_id_seq owned by otp.id;

