INSERT INTO port_type (id, name_ar, name_en)
VALUES (1, 'منفذ بحري', 'Sea Exit'),
       (2, 'سكة حديدية', 'Railway'),
       (3, 'منفذ بري', 'Land Exit'),
       (4, 'منفذ جوي', 'Air Exit');
-- ============================================================================
-- INSERT DATA INTO port
-- Flyway Migration Script
-- ============================================================================

INSERT INTO port (port_code, fk_port_type_id, code_desc_ar, code_desc_en)
VALUES ('75', 1, 'جمرك ميناء الملك عبد الله', 'King Abdullah Sea Port'),
       ('20', 4, 'جمرك مطار الملك فهد الدولي', 'KING FAHAD INTERNATIONAL AIRPORT CUSTOMS'),
       ('72', 4, 'جمرك مطار شروره', 'none'),
       ('63', 3, 'جمرك الخوبة', 'AL KHOBAH CUSTOMS'),
       ('74', 4, 'جمرك مطار العلا الدولي', 'AlUla International Airport'),
       ('94', 4, 'جمرك مطار الجوف', 'Aljouf Air Port'),
       ('51', 3, 'جمرك حالة عمار', 'Halat Ammar Land Port'),
       ('44', 3, 'جمرك الخفجي', 'Khafji land Port'),
       ('67', 3, 'جمرك علب', 'Alab Land Port'),
       ('62', 3, 'جمرك الموسم', 'AL MAWSIM CUSTOMS'),
       ('91', 3, 'جمرك طريف', 'Tareef Air Port'),
       ('52', 4, 'مطار البحر الاحمر  الدولي', 'Red Sea International Airport'),
       ('17', 1, 'جمرك ميناء ينبع التجاري', 'Yanbu Commercial Sea Port'),
       ('25', 4, 'جمرك مطار حائل', 'Hael Air Port'),
       ('69', 3, 'جمرك الخضراء', 'Alkhadrah land Port'),
       ('96', 1, 'جمرك ميناء رابغ', 'Rabig Sea Port'),
       ('11', 4, 'جمرك مطارالملك عبدالعزيزالدولي', 'King Abdul Aziz AirPort'),
       ('999', 1, 'الجهاز الرئيس', 'الجهاز الرئيس'),
       ('50', 4, 'جمرك مطارالأميرسلطان بن عبدالعزيز', 'Prince Sultan bin Abdulaziz Air Port'),
       ('90', 3, 'جمرك جديدة عرعر', 'Aar''ar Land Port'),
       ('24', 4, 'جمرك مطار الطائف', 'Altaef Air Port'),
       ('84', 3, 'جمرك فرسان', 'FARASAN CUSTOMS'),
       ('18', 4, 'جمرك مطار ينبع', 'Yanbu Air Port .'),
       ('29', 4, 'جمرك مطار الأحساء الدولي', 'Al Hasa Air Port'),
       ('40', 4, 'جمرك مطار القيصومة الدولي', 'Al Qaisumah AirPort'),
       ('21', 4, 'مطار الأمير محمد بن عبدالعزيز', 'PRINCE MOHAMMED BIN ABDULAZIZ AIRPORT'),
       ('16', 1, 'ميناء جازان للصناعات الأساسية والتحويلية', 'Jazan for Primary and Downstream Industr'),
       ('35', 3, 'جمرك الرقعي', 'Al Raqee land Port'),
       ('45', 1, 'جمرك ميناء الجبيل الصناعي', 'Jubail Industrial Sea Port'),
       ('47', 1, 'جمرك ميناء الخفجي', 'Khafji Sea Port'),
       ('22', 4, 'جمرك مطار القصيم', 'QASIM AIRPORT CUSTOMS'),
       ('60', 1, 'جمرك ميناء جيزان', 'Jazan Sea Port'),
       ('13', 4, 'جمرك مطار نيوم', 'Neom Air Port'),
       ('14', 4, 'جمرك قاعدة الأمير سلطان الجوية', 'none'),
       ('95', 3, 'جمرك الحديثة', 'Alhaditha Land Port'),
       ('48', 3, 'جمرك الربع الخالي', 'Rub''a Khali land Port'),
       ('64', 4, 'جمرك مطار الملك عبدالله بجازان', 'Kingdom Abdulla jazan airport'),
       ('10', 1, 'جمرك ميناء جده الاسلامي', 'Jedah Islamic Sea Port'),
       ('100', 4, 'جمرك مطار حائل', 'Hael Airport'),
       ('71', 4, 'جمرك مطار أبها', 'Abha Air Port'),
       ('43', 1, 'جمرك راس مشعاب', 'RAS MISHA''AB CUSTOMS'),
       ('23', 4, 'جمرك مطار الملك خالد الدولي', 'KING KHALED INTERNATIONAL AIRPORT CUSTOMS '),
       ('66', 3, 'جمرك الوديعة', 'Alwadeeaa land Port'),
       ('83', 3, 'جمرك جسر الملك فهد', 'King Fahid Cousway'),
       ('32', 1, 'جمرك ميناء رأس تنوره', 'Ras Tanorah Sea Port'),
       ('42', 1, 'جمرك محافظة الجبيل', 'Aljubail Sea Port'),
       ('53', 1, 'جمرك ميناء نيوم', 'Neom Sea Port'),
       ('61', 3, 'جمرك الطوال', 'Twal land Port'),
       ('19', 1, 'جمرك ميناء الملك فهد الصناعي', 'Yanbu Sea Port Indus.'),
       ('54', 3, 'جمرك الدره', 'Dorah Land Port'),
       ('85', 1, 'جمرك ميناء سنداله', 'Sindalh  Sea Port'),
       ('31', 3, 'جمرك البطحاء', 'Batha Land Port'),
       ('33', 1, 'جمرك رأس الخير', 'Ras Alkhair sea Port'),
       ('73', 4, 'جمرك مطار نجران', 'none'),
       ('30', 1, 'جمرك ميناء الملك عبدالعزيز', 'King Abdul Aziz Sea Port'),
       ('34', 2, 'جمرك الرياض - الميناء الجاف', 'Dry Port'),
       ('36', 3, 'جمرك العديد', 'AL-ODAID CUSTOMS'),
       ('41', 3, 'جمرك سلوى', 'Salwa land Port'),
       ('55', 4, 'مطار عرعر المحلي', 'Arar Domestic Airport'),
       ('56', 4, 'مطار الوجه المحلي', 'Al Wajh Domestic Airport'),
       ('12', 4, 'جمرك مطار نجران', 'Najran Air Port'),
       ('15', 4, 'جمرك مطار الملك عبدالله بجازان', 'King Abdulla jazan airport');
